// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOeO1fdJ7p2lVKwe55bDfHmguJzeU2po',
    appId: '1:994557648197:web:8cb9b5366454d61c2c322c',
    messagingSenderId: '994557648197',
    projectId: 'asilation-6f2dc',
    authDomain: 'asilation-6f2dc.firebaseapp.com',
    storageBucket: 'asilation-6f2dc.appspot.com',
    measurementId: 'G-LCP3DN1BPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCKI_f7Lbkjxntw-C8g9RMQrmf2ei1U4',
    appId: '1:994557648197:android:40a6402f6c18254d2c322c',
    messagingSenderId: '994557648197',
    projectId: 'asilation-6f2dc',
    storageBucket: 'asilation-6f2dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA36oGx6IKwBvoF-r6_KJpsOazkjwzMk2U',
    appId: '1:994557648197:ios:d29537ba3efcfaec2c322c',
    messagingSenderId: '994557648197',
    projectId: 'asilation-6f2dc',
    storageBucket: 'asilation-6f2dc.appspot.com',
    iosClientId: '994557648197-17qmcfljq349im368lkl1qgsjdnrqqg5.apps.googleusercontent.com',
    iosBundleId: 'com.asilation.qatar.asilation',
  );
}
